name: "Labels"
description: "Adds labels"
author: "gjtorikian"
inputs:
  repo-token:
    description: "Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}"
    required: true
runs:
  using: "node12"
  main: "main.js"
